apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-reader-user
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: ""
